### ISSUE TITLE
Final UI changes

### ISSUE THREAD

**Issue by dartpain** [arc53/DocsGPT#121]
@tenokami 

- [x] 1. Reducing font size and maybe increasing line spacing will improve readability. Use figma as a reference 
![image](https://user-images.githubusercontent.com/15183589/221141978-1c73601d-4fe6-4973-9c2e-e7fe656cea53.png)

- [x] 2. I'd put this lower to be more in line with the user's eye level. Use figma as a reference (Worked on #120)
![image](https://user-images.githubusercontent.com/15183589/221150649-d30519e9-c3ff-4373-aa48-70f77ba5fecb.png)

- [x] 3. Selecting source documentation isn't like in Figma. I'm not sure if you changed it deliberately  WIP #122 
![image](https://user-images.githubusercontent.com/15183589/221150761-385c454b-3a6e-4783-a7d1-e0865c7e52f0.png)

- [x] 4. Since it lacks the chat button from figma, there is no way to come back from the About page (Worker on #120)
![image](https://user-images.githubusercontent.com/15183589/221150937-db16391c-7cc2-47b2-b8ce-46b03c8ebcf4.png)

- [x] 5. If u change the source documentation select in the sidebar, then a lot of space will be freed and we can make the sidebar take less space WIP

- [x] 6. Making the input field larger can make it easier to spot and there is no text under it like in figma
![image](https://user-images.githubusercontent.com/15183589/221151134-df27677b-1662-4cb1-953e-b19a5f6c4b74.png)

- [x] 7. this is not the end of the world, but in figma, the fonts here are intentionally not purely black WIP
![image](https://user-images.githubusercontent.com/15183589/221151269-6b7eb744-4dd1-4f90-b972-e6fb9c869a14.png)

- [x] 8. The dividing lines are a little too hard to spot. Consider making them darker like they look in figma. This includes all lines of this type 
![image](https://user-images.githubusercontent.com/15183589/221151387-7c93c492-ae81-44ee-9a8f-7e781fefaef6.png)

- [x] 9. The about page looks very different from the design. Please consider making it look more similar. And don't forget to add all links WIP

![image](https://user-images.githubusercontent.com/15183589/221151473-b4403a81-2894-4e1c-b31f-4c42af5d5c21.png)

- [x] 10. Discord and Github buttons in sidebar aren't working WIP #122 
- [x] 11. Clicking "Enter" should act like sending the message and not as "next line" WIP

- [x] 12. Rn, if u send a message in two separate lines, then the result will display in one line. Lines should be the same as they were inputed by the user.
![image](https://user-images.githubusercontent.com/15183589/221151708-346926d7-9d12-47de-916f-65ebf4f89036.png)

- [x] 13. Design update: Moved the user's message to the right, and put a purple background under it WIP
![image](https://user-images.githubusercontent.com/15183589/221151835-1c5c7ecd-2ded-4cb7-a1aa-9bda555fcee3.png)

- [x] 14. On mobile, the hamburger icon has to be separated with a line similarly to chatgpt WIP
![image](https://user-images.githubusercontent.com/15183589/221152006-75e63322-6cad-417e-b0c8-99ae9ecd6ed5.png)

- [x] 15. Little arrow on dropdown WIP
<img width="323" alt="image" src="https://user-images.githubusercontent.com/15183589/221190932-066212b2-4bba-401e-9dc5-66c2c25a3dbb.png">
